### ISSUE TITLE
Final styling

### ISSUE THREAD

**Issue by emeliesv** [emeliesv/Jenyf-Studios#64]

**Comment by johannabra** [comment]
consistent syntax in styling
(tailwind)

**Comment by johannabra** [comment]
hover to primary bg

**Comment by johannabra** [comment]
button 3 sizes sm, md, lg

**Comment by johannabra** [comment]
- width 100% productlist
- hello fall smaler font 
- landingpage text line to the left
- margin breadcrums and category and productcard, product list

**Comment by johannabra** [comment]
checkout card width

**Comment by emeliesv** [comment]
Sim-kort electronics /s wrong route - only this product because of the /S
pagination - refactor so that on categorylist it shows only the right amount of pages
Set max-height for productinfo (see bracelet-img)

**Comment by emeliesv** [comment]
Add to cart not working properly. should remove link around productcard.
